# Generated by Django 4.2.7 on 2026-06-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gastos_diarios', '0003_gastodiario_tipo_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('visita', 'Visita'), ('vencimiento', 'Vencimiento'), ('cobro', 'Cobro'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento')),
                ('hora_envio', models.TimeField(verbose_name='Hora de envío')),
                ('anticipacion_dias', models.PositiveIntegerField(default=0, help_text='Avisar X días antes de la fecha. Solo aplica a eventos sin repetir.', verbose_name='Anticipación (días antes)')),
                ('recurrencia', models.CharField(choices=[('ninguna', 'Sin repetir'), ('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='ninguna', max_length=20, verbose_name='Recurrencia')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Último envío')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(related_name='eventos_agenda', to='gastos_diarios.numeroautorizado', verbose_name='Destinatarios')),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Eventos de agenda',
                'ordering': ['fecha_evento', 'hora_envio'],
            },
        ),
    ]
