# Generated by Django 4.2.7 on 2026-06-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0023_tipocuenta_caja_chica'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda', to='comercial.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
