# Generated by Django 4.2.7 on 2026-06-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_eventoagenda_cliente_eventoagenda_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoagenda',
            name='tipo',
            field=models.CharField(choices=[('mediciones', 'Mediciones'), ('servicio_tecnico', 'Servicio técnico'), ('pendientes', 'Pendientes'), ('llamar', 'Llamar'), ('colocaciones', 'Colocaciones')], default='pendientes', max_length=20, verbose_name='Tipo'),
        ),
    ]
