# Generated by Django 4.2.7 on 2026-06-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0023_tipocuenta_caja_chica'),
        ('agenda', '0003_tipo_choices_nuevos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoagenda',
            name='recurrencia',
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='colocador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda', to='comercial.cuenta', verbose_name='Colocador'),
        ),
    ]
