# Generated by Django 4.2.7 on 2026-06-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0004_remove_recurrencia_add_colocador'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsable'),
        ),
    ]
