# Generated by Django 6.0.4 on 2026-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_eventoagenda_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='hora_evento',
            field=models.TimeField(blank=True, help_text='Hora en que ocurre el evento (colocación, visita, etc.). Opcional.', null=True, verbose_name='Horario del evento'),
        ),
    ]
