services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: akuna_calc
      MYSQL_USER: akuna
      MYSQL_PASSWORD: akuna123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    command: >
      --innodb-buffer-pool-size=128M
      --innodb-log-file-size=32M
      --innodb-flush-method=O_DSYNC
      --innodb-flush-log-at-trx-commit=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      DB_NAME: akuna_calc
      DB_USER: akuna
      DB_PASSWORD: akuna123
      DB_HOST: db
      DB_PORT: 3306
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
      DEBUG: "true"
      TELEGRAM_BOT_SECRET: "akuna-bot-secret-2024"
    depends_on:
      - db
    volumes:
      - ./akuna_calc:/app

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://mya-hypernatural-dalton.ngrok-free.dev
      - N8N_EDITOR_BASE_URL=https://mya-hypernatural-dalton.ngrok-free.dev
    volumes:
      - n8n_data:/home/node/.n8n

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

volumes:
  mysql_data:
  n8n_data:
