# Generated by Django 6.0.4 on 2026-07-18 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSolicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ultimo_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Último vendedor asignado')),
            ],
            options={
                'verbose_name': 'Configuración de solicitudes',
                'verbose_name_plural': 'Configuración de solicitudes',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=200, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('asunto', models.CharField(blank=True, max_length=300, verbose_name='Asunto')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('contestada', 'Contestada'), ('sin_asignar', 'Sin asignar')], default='asignada', max_length=20, verbose_name='Estado')),
                ('origen', models.CharField(default='email', max_length=30, verbose_name='Origen')),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ID de hilo de Gmail')),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de recepción')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('fecha_contestada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('ultimo_recordatorio', models.DateTimeField(blank=True, null=True, verbose_name='Último recordatorio')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_presupuesto', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado')),
            ],
            options={
                'verbose_name': 'Solicitud de presupuesto',
                'verbose_name_plural': 'Solicitudes de presupuesto',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
