# Generated by Django 4.2.7 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '000X_add_recibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Recibo', 'verbose_name_plural': 'Recibos'},
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Nro. Recibo'),
        ),
    ]
