# Generated by Django 4.2.7 on 2026-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='monto_cobrado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], default='CF', max_length=4),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='compra',
            name='con_factura',
            field=models.BooleanField(default=True, verbose_name='Compra en blanco (con factura)'),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='condicion_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final')], max_length=4),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuit',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='venta',
            name='con_factura',
            field=models.BooleanField(default=True, verbose_name='Venta en blanco (con factura)'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_pedido',
            field=models.CharField(max_length=50),
        ),
    ]
