# Generated by Django 4.2.20 on 2026-01-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_cliente_deleted_at_compra_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuenta',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubTipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='comercial.tipocuenta')),
            ],
            options={
                'verbose_name': 'Sub Tipo de Cuenta',
                'verbose_name_plural': 'Sub Tipos de Cuenta',
                'ordering': ['nombre'],
            },
        ),
    ]
