# Generated by Django 4.2.20 on 2026-01-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_tipocuenta_deleted_at_subtipocuenta'),
    ]

    operations = [
        # Solo agregar el campo tipo_gasto a Compra
        migrations.AddField(
            model_name='compra',
            name='tipo_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.subtipocuenta'),
        ),
    ]
