# Generated by Django 5.1.3 on 2026-01-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0006_tipogasto_delete_subtipocuenta_compra_tipo_gasto"),
    ]

    # 0006 already creates compra.tipo_gasto. After 0008 renames
    # SubTipoCuenta to TipoGasto, Django state follows that rename without
    # needing a second SQL AddField on fresh databases.
    operations = []
