# Generated by Django 5.1.3 on 2026-01-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0006_tipogasto_delete_subtipocuenta_compra_tipo_gasto"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="tipo_gasto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comercial.tipogasto",
            ),
        ),
    ]
