# Generated by Django 4.2.7 on 2026-01-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_tipogasto_delete_subtipocuenta_compra_tipo_gasto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubTipoCuenta',
            new_name='TipoGasto',
        ),
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'verbose_name': 'Tipo de Gasto', 'verbose_name_plural': 'Tipos de Gasto', 'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='tipogasto',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_gasto', to='comercial.tipocuenta'),
        ),
    ]
