# Generated by Django 4.2.7 on 2026-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_rename_subtipocuenta_to_tipogasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Factura'),
        ),
        migrations.AlterModelTable(
            name='tipogasto',
            table='comercial_subtipocuenta',
        ),
    ]
