# Generated by Django 5.1.3 on 2026-01-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0007_compra_tipo_gasto"),
        ("comercial", "0008_rename_subtipocuenta_to_tipogasto"),
    ]

    operations = []
