# Generated by Django 4.2.7 on 2026-04-27
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('comercial', '0016_compra_forma_pago_sena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(max_digits=12, decimal_places=2)),
                ('importe_letras', models.CharField(max_length=300)),
                ('concepto', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='recibos/', blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.venta', related_name='recibos')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.pagoventa', related_name='recibos')),
            ],
        ),
    ]
