# Generated by Django 5.1.3 on 2026-01-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0009_merge_20260130_1421"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tipogasto",
            table="comercial_subtipocuenta",
        ),
    ]
