# Generated by Django 4.2.7 on 2026-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_pagoventa_numero_factura_alter_tipogasto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_retenciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto de retenciones'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tiene_retenciones',
            field=models.BooleanField(default=False, verbose_name='Tiene retenciones'),
        ),
    ]
