# Generated by Django 4.2.7 on 2026-02-04 09:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_venta_monto_retenciones_venta_tiene_retenciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganancias', 'Ganancias'), ('iibb', 'Ingresos Brutos'), ('iva', 'IVA'), ('seguridad_social', 'Seguridad Social'), ('otros', 'Otros')], max_length=20)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('importe_isar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Importe ISAR (Base)')),
                ('importe_retenido', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe Retenido')),
                ('fecha_comprobante', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='comercial.pagoventa')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
            },
        ),
        migrations.CreateModel(
            name='Percepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganancias', 'Ganancias'), ('iibb_ba', 'Ingresos Brutos Buenos Aires'), ('iibb_caba', 'Ingresos Brutos CABA'), ('iva', 'IVA')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percepciones', to='comercial.venta')),
            ],
            options={
                'verbose_name': 'Percepción',
                'verbose_name_plural': 'Percepciones',
            },
        ),
    ]
