# Generated by Django 5.1.3 on 2026-02-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0010_alter_tipogasto_table"),
        ("comercial", "0010_venta_monto_retenciones_venta_tiene_retenciones"),
    ]

    operations = []
