# Generated by Django 5.1.3 on 2026-02-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0011_merge_20260203_0830"),
        ("comercial", "0011_retencion_percepcion"),
    ]

    operations = []
