# Generated by Django 4.2.7 on 2026-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_retencion_percepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='con_factura',
            field=models.BooleanField(default=True, verbose_name='Pago en blanco (con factura)'),
        ),
    ]
