# Generated by Django 5.1.3 on 2026-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0012_merge_20260217_1229"),
    ]

    # 0012_pagoventa_con_factura already adds pagoventa.con_factura.
    # Keep this branch in the graph without issuing duplicate SQL on clean DBs.
    operations = []
