# Generated by Django 5.1.3 on 2026-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0012_merge_20260217_1229"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoventa",
            name="con_factura",
            field=models.BooleanField(
                default=True, verbose_name="Pago en blanco (con factura)"
            ),
        ),
    ]
