# Generated by Django 4.2.7 on 2026-03-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_pagoventa_con_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
    ]
