# Generated by Django 4.2.7 on 2026-03-28 16:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comercial', '0013_venta_notas_internas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='importe_abonado',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AddField(
            model_name='compra',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='sena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago', models.DateField()),
                ('forma_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('con_factura', models.BooleanField(default=True, verbose_name='Pago en blanco (con factura)')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_compra', to='comercial.compra')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
