# Generated by Django 5.1.3 on 2026-03-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0012_pagoventa_con_factura"),
        ("comercial", "0013_pagoventa_con_factura"),
    ]

    operations = []
