# Generated by Django 4.2.7 on 2026-04-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_rename_importe_abonado_compra_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='cotizacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD utilizada'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='monto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='pago_en_dolares',
            field=models.BooleanField(default=False, verbose_name='Pagó en dólares'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
    ]
