# Generated by Django 5.1.3 on 2026-03-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0013_venta_notas_internas"),
        ("comercial", "0014_merge_20260306_1213"),
    ]

    operations = []
