# Generated by Django 5.1.3 on 2026-03-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0014_rename_importe_abonado_compra_valor_total_and_more"),
        ("comercial", "0015_merge_20260307_0939"),
    ]

    operations = []
