# Generated by Django 5.1.3 on 2026-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0016_merge_20260329_0826"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="fecha_factura",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Factura"
            ),
        ),
    ]
