# Generated by Django 5.1.3 on 2026-04-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0016_compra_forma_pago_sena"),
        ("comercial", "0017_venta_fecha_factura"),
    ]

    operations = []
