# Generated by Django 5.1.3 on 2026-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0018_merge_20260421_0917"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagoventa",
            name="fecha_factura",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Factura"
            ),
        ),
    ]
