# Generated by Django 5.1.3 on 2026-04-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comercial", "0001_alter_recibo_options_pagoventa_fecha_factura_and_more"),
        ("comercial", "0019_pagoventa_fecha_factura"),
    ]

    operations = []
