# Generated by Django 6.0.4 on 2026-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_merge_20260427_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='compra_en_dolares',
            field=models.BooleanField(default=False, verbose_name='Compra en dólares'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cotizacion_sena_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD de la seña'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cotizacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD utilizada'),
        ),
        migrations.AddField(
            model_name='compra',
            name='sena_en_dolares',
            field=models.BooleanField(default=False, verbose_name='Seña en dólares'),
        ),
        migrations.AddField(
            model_name='compra',
            name='sena_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Seña en USD'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total en USD'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='cotizacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD utilizada'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='monto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en USD'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='pago_en_dolares',
            field=models.BooleanField(default=False, verbose_name='Pagó en dólares'),
        ),
    ]
