# Generated by Django 6.0.4 on 2026-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_compra_compra_en_dolares_compra_cotizacion_sena_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cotizacion_sena_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD de la seña'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cotizacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD utilizada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sena_en_dolares',
            field=models.BooleanField(default=False, verbose_name='Seña en dólares'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sena_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Seña en USD'),
        ),
        migrations.AddField(
            model_name='venta',
            name='valor_total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total en USD'),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_en_dolares',
            field=models.BooleanField(default=False, verbose_name='Venta en dólares'),
        ),
    ]
