# Generated by Django 4.2.7 on 2026-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Sin el sufijo @s.whatsapp.net. Ej: 5491155555555', max_length=30, unique=True, verbose_name='Número de WhatsApp')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre / Referencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Número autorizado',
                'verbose_name_plural': 'Números autorizados',
                'ordering': ['nombre', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='GastoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_espera', max_length=20, verbose_name='Estado')),
                ('numero_origen', models.CharField(max_length=30, verbose_name='Número origen')),
                ('audio_id', models.CharField(blank=True, max_length=120, verbose_name='ID de audio (WhatsApp)')),
                ('transcripcion', models.TextField(blank=True, verbose_name='Transcripción del audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gasto diario',
                'verbose_name_plural': 'Gastos diarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audio_id', 'numero_origen'], name='gd_audio_numero_idx')],
            },
        ),
    ]
