# Generated by Django 4.2.7 on 2026-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_diarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastodiario',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_espera', 'En espera'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_espera', max_length=20, verbose_name='Estado'),
        ),
    ]
