# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_diarios', '0002_alter_gastodiario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastodiario',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('colocadores', 'Colocadores'), ('colaboradores', 'Colaboradores'), ('fletes', 'Fletes'), ('retiros_propios', 'Retiros Propios'), ('varios', 'Varios'), ('proveedores', 'Proveedores'), ('caja_chica', 'Caja Chica')], help_text='Tipo de cuenta donde se registra el gasto al aprobarlo. Vacío = sin clasificar.', max_length=20, verbose_name='Clasificación (Tipo de Cuenta)'),
        ),
    ]
