# Generated by Django 4.2.7 on 2026-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('codigo', models.TextField(db_column='COD_PARTE', primary_key=True, serialize=False)),
                ('color_id', models.IntegerField(blank=True, db_column='Idcolor', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRI', null=True)),
                ('precio', models.FloatField(blank=True, db_column='PRECIO', null=True)),
                ('contenido', models.FloatField(blank=True, db_column='CONTENIDO', null=True)),
                ('unidad', models.FloatField(blank=True, db_column='UNIDAD', null=True)),
                ('moneda', models.IntegerField(blank=True, db_column='MONEDA', null=True)),
                ('bloqueado', models.TextField(blank=True, db_column='Bloqueado', null=True)),
                ('tipo', models.IntegerField(blank=True, db_column='Tipo', null=True)),
            ],
            options={
                'db_table': 'accesorios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contravidrio',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
            ],
            options={
                'db_table': 'contravidrio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContravidrioExterior',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
            ],
            options={
                'db_table': 'contravidrio_exterior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cruce',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
            ],
            options={
                'db_table': 'cruces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosContravidrio',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_contravidrio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosContravidrioExterior',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_contravidrio_exterior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosCruces',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_cruces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosHoja',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('idconjunto', models.IntegerField(blank=True, db_column='Idconjunto', null=True)),
                ('nombre_conjunto', models.TextField(blank=True, db_column='Nombre_conjunto', null=True)),
                ('aparece_presupuesto', models.TextField(blank=True, db_column='Aparece_presupuesto', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_hoja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosInterior',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
                ('id_conjunto', models.IntegerField(blank=True, db_column='id_conjunto', null=True)),
                ('nombre_conjunto', models.TextField(blank=True, db_column='nombre_conjunto', null=True)),
                ('bur_int', models.TextField(blank=True, db_column='bur_int', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_interior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosMarco',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_marco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosMosquitero',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_mosquitero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceAccesoriosVidrioRepartido',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('accesorio', models.TextField(blank=True, db_column='Accesorio', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_accesorios_vidrio_repartido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceCruces',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('formula_ancho_entero', models.TextField(blank=True, db_column='Formuladeanchoentero', null=True)),
                ('formula_alto_entero', models.TextField(blank=True, db_column='Formuladealtoentero', null=True)),
                ('descuento_vidrio', models.IntegerField(blank=True, db_column='Descuentodevidrio', null=True)),
                ('descuento_desimismo', models.IntegerField(blank=True, db_column='Descuentodesimismo', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('diferencia_con_marco', models.IntegerField(blank=True, db_column='Diferenciaconmarco_marco', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
                ('esp_cruce', models.FloatField(blank=True, db_column='esp_cruce', null=True)),
            ],
            options={
                'db_table': 'despiece_cruces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceInterior',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formulacantidadinteriores', null=True)),
                ('formula_ancho', models.TextField(blank=True, db_column='Formulaanchointerior', null=True)),
                ('formula_alto', models.TextField(blank=True, db_column='Formulaaltointerior', null=True)),
                ('descuento_izquierda', models.IntegerField(blank=True, db_column='Descuentoizquierda', null=True)),
                ('descuento_derecha', models.IntegerField(blank=True, db_column='Descuentoderecha', null=True)),
                ('descuento_abajo', models.IntegerField(blank=True, db_column='Descuentoabajo', null=True)),
                ('descuento_arriba', models.IntegerField(blank=True, db_column='Descuentoarriba', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_interior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespieceInteriorMosquitero',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formulacantidadinteriores', null=True)),
                ('formula_ancho', models.TextField(blank=True, db_column='Formulaanchointerior', null=True)),
                ('formula_alto', models.TextField(blank=True, db_column='Formulaaltointerior', null=True)),
                ('descuento_izquierda', models.IntegerField(blank=True, db_column='Descuentoizquierda', null=True)),
                ('descuento_derecha', models.IntegerField(blank=True, db_column='Descuentoderecha', null=True)),
                ('descuento_abajo', models.IntegerField(blank=True, db_column='Descuentoabajo', null=True)),
                ('descuento_arriba', models.IntegerField(blank=True, db_column='Descuentoarriba', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_interior_mosquitero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespiecePerfilesContravidrio',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_cantidad_ancho', models.TextField(blank=True, db_column='Formulacantidadcontravidriosancho', null=True)),
                ('formula_cantidad_alto', models.TextField(blank=True, db_column='Formulacantidadcontravidriosalto', null=True)),
                ('formula_ancho', models.TextField(blank=True, db_column='Formulacontravidrioancho', null=True)),
                ('formula_alto', models.TextField(blank=True, db_column='Formulacontravidrioalto', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
                ('altura_contravidrio', models.IntegerField(blank=True, db_column='altura_contravidrio', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_contravidrios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespiecePerfilesContravidrioExterior',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_cantidad_ancho', models.TextField(blank=True, db_column='Formulacantidadcontravidriosancho', null=True)),
                ('formula_cantidad_alto', models.TextField(blank=True, db_column='Formulacantidadcontravidriosalto', null=True)),
                ('formula_ancho', models.TextField(blank=True, db_column='Formulacontravidrioancho', null=True)),
                ('formula_alto', models.TextField(blank=True, db_column='Formulacontravidrioalto', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
                ('altura_contravidrio', models.IntegerField(blank=True, db_column='altura_contravidrio', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_contravidrios_exterior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespiecePerfilesHoja',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_perfil', models.TextField(blank=True, db_column='Formuladeperfil', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_hojas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespiecePerfilesMarco',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_perfil', models.TextField(blank=True, db_column='Formuladeperfil', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_marcos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespiecePerfilesMosquitero',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_perfil', models.TextField(blank=True, db_column='Formuladeperfil', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_mosquitero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespiecePerfilesVidrioRepartido',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('perfil_contorno', models.TextField(blank=True, db_column='Perfildecontorno', null=True)),
                ('formula_cantidad_contorno_ancho', models.TextField(blank=True, db_column='Formulacantidadcontornoancho', null=True)),
                ('formula_cantidad_contorno_alto', models.TextField(blank=True, db_column='Formulacantidadcontornoalto', null=True)),
                ('formula_contorno_ancho', models.TextField(blank=True, db_column='Formulacontornoancho', null=True)),
                ('formula_contorno_alto', models.TextField(blank=True, db_column='Formulacontornoalto', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('perfil_cruce', models.TextField(blank=True, db_column='Perfildecruce', null=True)),
                ('formula_cruce_ancho', models.TextField(blank=True, db_column='Formulacruceancho', null=True)),
                ('formula_cruce_alto', models.TextField(blank=True, db_column='Formulacrucealto', null=True)),
                ('descuento_vidrio', models.FloatField(blank=True, db_column='Descuentodevidrio', null=True)),
                ('descuento_desimismo', models.FloatField(blank=True, db_column='Descuentodesi', null=True)),
                ('angulo_cruce', models.TextField(blank=True, db_column='Angulocruce', null=True)),
                ('formula_cantidad_interiores', models.TextField(blank=True, db_column='Formulacantidadinteriores', null=True)),
                ('formula_ancho_interior', models.TextField(blank=True, db_column='Formulaanchointerior', null=True)),
                ('formula_alto_interior', models.TextField(blank=True, db_column='Formulaaltointerior', null=True)),
                ('descuento_izquierda', models.IntegerField(blank=True, db_column='Descuentoizquierda', null=True)),
                ('descuento_derecha', models.IntegerField(blank=True, db_column='Descuentoderecha', null=True)),
                ('descuento_abajo', models.IntegerField(blank=True, db_column='Descuentoabajo', null=True)),
                ('descuento_arriba', models.IntegerField(blank=True, db_column='Descuentoarriba', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_vidrio_repartido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extrusora',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='Extrusora', null=True)),
                ('bloqueado', models.TextField(blank=True, db_column='Bloqueado', null=True)),
            ],
            options={
                'db_table': 'extrusoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoja',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
            ],
            options={
                'db_table': 'hoja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
            ],
            options={
                'db_table': 'interior',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, db_column='L_nea', null=True)),
                ('bloqueado', models.TextField(blank=True, db_column='Bloqueado', null=True)),
            ],
            options={
                'db_table': 'l_neas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
                ('forma_dibujo', models.IntegerField(blank=True, db_column='forma_dibujo', null=True)),
            ],
            options={
                'db_table': 'marco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mosquitero',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
            ],
            options={
                'db_table': 'mosquitero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('codigo', models.TextField(db_column='NRO_PERFIL', primary_key=True, serialize=False)),
                ('linea_id', models.IntegerField(blank=True, db_column='Idl_nea', null=True)),
                ('color_id', models.IntegerField(blank=True, db_column='COD_COLOR', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRI', null=True)),
                ('peso_metro', models.FloatField(blank=True, db_column='PESO_METRO', null=True)),
                ('long_tira', models.IntegerField(blank=True, db_column='LONG_TIRA', null=True)),
                ('precio_kg', models.FloatField(blank=True, db_column='PRECIO_KG', null=True)),
                ('long_alt', models.FloatField(blank=True, db_column='LONG_ALT', null=True)),
                ('corte45', models.FloatField(blank=True, db_column='CORTE45', null=True)),
                ('interior', models.TextField(blank=True, db_column='INTERIOR', null=True)),
                ('tipo', models.FloatField(blank=True, db_column='TIPO', null=True)),
                ('material', models.FloatField(blank=True, db_column='MATERIAL', null=True)),
                ('moneda', models.IntegerField(blank=True, db_column='MONEDA', null=True)),
                ('cubre', models.IntegerField(blank=True, db_column='cubre', null=True)),
                ('bloqueado', models.TextField(blank=True, db_column='Bloqueado', null=True)),
                ('minimo_reutilizable', models.TextField(blank=True, db_column='minimo_reutilizable', null=True)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('idtipo', models.IntegerField(blank=True, db_column='Idtipo', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('fecha_creacion', models.TextField(blank=True, db_column='Fecha_creacion', null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('precio_kg', models.FloatField(blank=True, db_column='Precioporkilo', null=True)),
                ('color_id', models.IntegerField(blank=True, db_column='color', null=True)),
                ('moneda', models.IntegerField(blank=True, db_column='MONEDA', null=True)),
                ('bloqueado', models.TextField(blank=True, db_column='Bloqueado', null=True)),
            ],
            options={
                'db_table': 'tratamientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vidrio',
            fields=[
                ('codigo', models.TextField(db_column='CODIGO', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRI', null=True)),
                ('precio', models.FloatField(blank=True, db_column='PRECIO', null=True)),
                ('base', models.IntegerField(blank=True, db_column='BASE', null=True)),
                ('altura', models.IntegerField(blank=True, db_column='ALTURA', null=True)),
                ('espesor', models.IntegerField(blank=True, db_column='ESPESOR', null=True)),
                ('moneda', models.IntegerField(blank=True, db_column='MONEDA', null=True)),
                ('tipo_rev', models.IntegerField(blank=True, db_column='TIPO_REV', null=True)),
                ('color_id', models.IntegerField(blank=True, db_column='color', null=True)),
                ('bloqueado', models.TextField(blank=True, db_column='Bloqueado', null=True)),
                ('maximo', models.IntegerField(blank=True, db_column='Maximo', null=True)),
                ('corte1', models.TextField(blank=True, db_column='Corte1', null=True)),
                ('transparente', models.TextField(blank=True, db_column='transparente', null=True)),
            ],
            options={
                'db_table': 'vidrios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidrioRepartido',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripci_n', null=True)),
                ('predeterminado', models.TextField(blank=True, db_column='Predeterminado', null=True)),
                ('no_verificado', models.TextField(blank=True, db_column='no_verificado', null=True)),
                ('interior_entero', models.TextField(blank=True, db_column='interior_entero', null=True)),
            ],
            options={
                'db_table': 'vidrio_repartido',
                'managed': False,
            },
        ),
    ]
