# Generated by Django 4.2.7 on 2026-03-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrusora',
            options={'managed': True},
        ),
    ]
