# Generated by Django 4.2.7 on 2026-03-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_extrusora_options'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS extrusoras (Id INT PRIMARY KEY, Extrusora TEXT, Bloqueado TEXT);
            CREATE TABLE IF NOT EXISTS l_neas (Id INT PRIMARY KEY, Idextrusora INT, L_nea TEXT, Bloqueado TEXT);
            CREATE TABLE IF NOT EXISTS productos (Id INT PRIMARY KEY, Idextrusora INT, Idlinea INT, Idtipo INT, Descripci_n TEXT, Fecha_creacion TEXT);
            CREATE TABLE IF NOT EXISTS marco (Id INT PRIMARY KEY, idproducto INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT, forma_dibujo INT);
            CREATE TABLE IF NOT EXISTS hoja (Id INT PRIMARY KEY, idmarco INT, Descripci_n TEXT, Cantidad INT, Predeterminado TEXT, no_verificado TEXT);
            CREATE TABLE IF NOT EXISTS interior (Id INT PRIMARY KEY, Idhoja INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT);
            CREATE TABLE IF NOT EXISTS perfiles (NRO_PERFIL VARCHAR(255) PRIMARY KEY, Idl_nea INT, COD_COLOR INT, DESCRI TEXT, PESO_METRO FLOAT, LONG_TIRA INT, PRECIO_KG FLOAT, LONG_ALT FLOAT, CORTE45 FLOAT, INTERIOR TEXT, TIPO FLOAT, MATERIAL FLOAT, MONEDA INT, cubre INT, Bloqueado TEXT, minimo_reutilizable TEXT);
            CREATE TABLE IF NOT EXISTS accesorios (COD_PARTE VARCHAR(255) PRIMARY KEY, Idcolor INT, DESCRI TEXT, PRECIO FLOAT, CONTENIDO FLOAT, UNIDAD FLOAT, MONEDA INT, Bloqueado TEXT, Tipo INT);
            CREATE TABLE IF NOT EXISTS vidrios (CODIGO VARCHAR(255) PRIMARY KEY, DESCRI TEXT, PRECIO FLOAT, BASE INT, ALTURA INT, ESPESOR INT, MONEDA INT, TIPO_REV INT, color INT, Bloqueado TEXT, Maximo INT, Corte1 TEXT, transparente TEXT);
            CREATE TABLE IF NOT EXISTS tratamientos (Id INT PRIMARY KEY, Descripci_n TEXT, Precioporkilo FLOAT, color INT, MONEDA INT, Bloqueado TEXT);
            CREATE TABLE IF NOT EXISTS contravidrio (Id INT PRIMARY KEY, idinterior INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT);
            CREATE TABLE IF NOT EXISTS contravidrio_exterior (Id INT PRIMARY KEY, idinterior INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT);
            CREATE TABLE IF NOT EXISTS mosquitero (Id INT PRIMARY KEY, idhoja INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT);
            CREATE TABLE IF NOT EXISTS cruces (Id INT PRIMARY KEY, Idinterior INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT);
            CREATE TABLE IF NOT EXISTS vidrio_repartido (Id INT PRIMARY KEY, idinterior INT, Descripci_n TEXT, Predeterminado TEXT, no_verificado TEXT, interior_entero TEXT);
            """,
            "DROP TABLE IF EXISTS vidrio_repartido, cruces, mosquitero, contravidrio_exterior, contravidrio, tratamientos, vidrios, accesorios, perfiles, interior, hoja, marco, productos, l_neas, extrusoras;"
        ),
    ]
