# Generated by Django 4.2.7 on 2026-03-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_despieceperfilesmarco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despieceperfilesmarco',
            options={'managed': False},
        ),
    ]
