# Generated by Django 5.1.3 on 2026-03-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0005_alter_accesorio_options_alter_contravidrio_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesorio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="contravidrio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="contravidrioexterior",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="cruce",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesorioscontravidrio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesorioscontravidrioexterior",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesorioscruces",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesorioshoja",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesoriosinterior",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesoriosmarco",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesoriosmosquitero",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceaccesoriosvidriorepartido",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despiececruces",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceinterior",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceinteriormosquitero",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceperfilescontravidrio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceperfilescontravidrioexterior",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceperfileshoja",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceperfilesmarco",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceperfilesmosquitero",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="despieceperfilesvidriorepartido",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="hoja",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="interior",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="linea",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="marco",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="mosquitero",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="perfil",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="tratamiento",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="vidrio",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="vidriorepartido",
            options={"managed": False},
        ),
    ]
