# Generated by Django 5.1.3 on 2026-03-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0005_alter_despieceperfilesmarco_options"),
        ("pricing", "0006_alter_accesorio_options_alter_contravidrio_options_and_more"),
    ]

    operations = []
