# Generated by Django 4.2.7 on 2026-04-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_vidrio_hoja'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespiecePerfilesVidrio',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('formula_cantidad', models.TextField(blank=True, db_column='Formuladecantidad', null=True)),
                ('perfil', models.TextField(blank=True, db_column='Perfil', null=True)),
                ('formula_perfil', models.TextField(blank=True, db_column='Formuladeperfil', null=True)),
                ('angulo', models.TextField(blank=True, db_column='Angulo', null=True)),
                ('mo_especifica', models.IntegerField(blank=True, db_column='Mo_especifica', null=True)),
            ],
            options={
                'db_table': 'despiece_perfiles_vidrios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VidrioHoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja', models.ForeignKey(db_column='hoja_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='vidrio_hojas', to='pricing.hoja')),
                ('vidrio', models.ForeignKey(db_column='vidrio_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='vidrio_hojas', to='pricing.vidrio')),
            ],
            options={
                'db_table': 'vidrio_hojas',
                'unique_together': {('vidrio', 'hoja')},
            },
        ),
    ]
