# Generated by Django 5.1.3 on 2026-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0007_merge_20260307_0939"),
    ]

    operations = [
        migrations.CreateModel(
            name="DespiecePerfilesVidrio",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="Id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "formula_cantidad",
                    models.TextField(
                        blank=True, db_column="Formuladecantidad", null=True
                    ),
                ),
                ("perfil", models.TextField(blank=True, db_column="Perfil", null=True)),
                (
                    "formula_perfil",
                    models.TextField(
                        blank=True, db_column="Formuladeperfil", null=True
                    ),
                ),
                ("angulo", models.TextField(blank=True, db_column="Angulo", null=True)),
                (
                    "mo_especifica",
                    models.IntegerField(
                        blank=True, db_column="Mo_especifica", null=True
                    ),
                ),
            ],
            options={
                "db_table": "despiece_perfiles_vidrios",
                "managed": False,
            },
        ),
    ]
