# Generated by Django 4.2.7 on 2026-03-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_add_horas_hombre_v2'),
        ('pricing', '0007_vidrio_hoja'),
    ]

    operations = [
    ]
