# Generated by Django 5.1.3 on 2026-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0006_add_horas_hombre"),
        ("pricing", "0008_despieceperfilesvidrio"),
    ]

    operations = []
