# Generated by Django 5.1.3 on 2026-03-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0007_vidrio_hoja"),
        ("pricing", "0009_merge_20260312_1211"),
    ]

    operations = []
