# Generated by Django 5.1.3 on 2026-03-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0010_merge_0007_vidrio_hoja_0009_merge_20260312_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="VidrioHoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hoja",
                    models.ForeignKey(
                        db_column="hoja_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vidrio_hojas",
                        to="pricing.hoja",
                    ),
                ),
                (
                    "vidrio",
                    models.ForeignKey(
                        db_column="vidrio_codigo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vidrio_hojas",
                        to="pricing.vidrio",
                    ),
                ),
            ],
            options={
                "db_table": "vidrio_hojas",
                "unique_together": {("vidrio", "hoja")},
            },
        ),
    ]
