# Generated by Django 5.1.3 on 2026-04-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0008_despieceperfilesvidrio_vidriohoja"),
        ("pricing", "0011_vidriohoja"),
    ]

    operations = []
