# Generated by Django 4.2.7 on 2026-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_add_formula_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alicuota_iva',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
    ]
