# Generated by Django 4.2.7 on 2026-01-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_venta_monto_cobrado_cliente_condicion_iva_and_more'),
        ('productos', '0004_producto_alicuota_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.cliente'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
