# Generated by Django 4.2.7 on 2026-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_cotizacion_cliente_cotizacionitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('creado', 'Creado'), ('vendido', 'Vendido'), ('desestimado', 'Desestimado')], default='creado', max_length=20),
        ),
    ]
