# Generated by Django 4.2.7 on 2026-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
