# Generated by Django 4.2.7 on 2026-03-11 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0013_venta_notas_internas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de expiración')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='comercial.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ancho_mm', models.IntegerField(verbose_name='Ancho (mm)')),
                ('alto_mm', models.IntegerField(verbose_name='Alto (mm)')),
                ('margen_porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Margen (%)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio total')),
                ('resultado_json', models.JSONField(default=dict, verbose_name='Detalle del cálculo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='presupuestos.presupuesto', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
    ]
