# Generated by Django 4.2.7 on 2026-05-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_merge_20260427_1909'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='comercial.venta', verbose_name='Venta asociada'),
        ),
    ]# Generated by Django 6.0.4 on 2026-05-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_merge_20260427_1909'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='comercial.venta', verbose_name='Venta asociada'),
        ),
    ]
