# Generated by Django 6.0.4 on 2026-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_presupuesto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='recargo_obra_nueva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Recargo obra nueva'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='recargo_renovacion_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Recargo renovación por unidad'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_obra',
            field=models.CharField(blank=True, choices=[('obra_nueva', 'Obra nueva'), ('renovacion', 'Renovación')], default='', max_length=20, verbose_name='Tipo de obra'),
        ),
    ]
