# Generated by Django 4.2.7 on 2026-05-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_presupuesto_recargo_obra_nueva_and_more'),
        ('presupuestos', '0003_presupuesto_soft_delete'),
    ]

    operations = [
    ]
