# Generated by Django 4.2.7 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_merge_20260511_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopresupuesto',
            name='prioridad',
            field=models.CharField(
                blank=True,
                choices=[('normal', 'Normal'), ('importante', 'Importante')],
                default='normal',
                max_length=20,
                verbose_name='Prioridad'
            ),
        ),
    ]
