# Generated by Django 6.0.4 on 2026-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_comentariopresupuesto_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='modalidad_sena',
            field=models.CharField(choices=[('50_50', '50% adelanto / 50% saldo'), ('70_30', '70% adelanto / 30% saldo')], default='50_50', max_length=10, verbose_name='Modalidad de seña'),
        ),
    ]
