# Generated by Django 4.2.7 on 2026-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_presupuesto_modalidad_sena'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cotizacion_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cotización USD'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_material',
            field=models.CharField(choices=[('aluminio', 'Aluminio'), ('pvc', 'PVC')], default='aluminio', max_length=20, verbose_name='Tipo de material'),
        ),
    ]
