# Generated by Django 4.2.7 on 2026-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_presupuesto_cotizacion_usd_presupuesto_tipo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='incluye_flete',
            field=models.BooleanField(default=False, verbose_name='Incluye flete'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='incluye_colocacion',
            field=models.BooleanField(default=False, verbose_name='Incluye colocación'),
        ),
    ]
