# Generated by Django 6.0.4 on 2026-07-23 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0011_presupuesto_updated_by'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuesto', to='solicitudes.solicitudpresupuesto', verbose_name='Solicitud de origen'),
        ),
    ]
