# Generated by Django 4.2.7 on 2026-02-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_login_attempts', models.IntegerField(default=5, help_text='Intentos máximos de login antes de bloqueo')),
                ('lockout_duration', models.IntegerField(default=30, help_text='Minutos de bloqueo tras exceder intentos')),
                ('session_timeout', models.IntegerField(default=60, help_text='Minutos de inactividad antes de cerrar sesión')),
                ('force_password_change_days', models.IntegerField(default=90, help_text='Días para forzar cambio de contraseña (0=desactivado)')),
                ('min_password_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('require_special_chars', models.BooleanField(default=False)),
                ('log_all_actions', models.BooleanField(default=True)),
                ('log_retention_days', models.IntegerField(default=365, help_text='Días para mantener logs')),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_frequency_hours', models.IntegerField(default=24)),
                ('backup_retention_days', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Seguridad',
                'verbose_name_plural': 'Configuración de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='security_lo_ip_addr_622cb0_idx'), models.Index(fields=['username', '-timestamp'], name='security_lo_usernam_6d99d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Dejar vacío para bloqueo permanente', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Bloqueada',
                'verbose_name_plural': 'IPs Bloqueadas',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento de login fallido'), ('VIEW', 'Visualizar'), ('EXPORT', 'Exportar'), ('PRINT', 'Imprimir')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='security_au_timesta_cbae00_idx'), models.Index(fields=['user', '-timestamp'], name='security_au_user_id_6d8368_idx'), models.Index(fields=['action', '-timestamp'], name='security_au_action_7867d2_idx')],
            },
        ),
    ]
