# Generated by Django 5.1.3 on 2026-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuraciongeneral",
            name="clave",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
