# Generated by Django 4.2.7 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='clave',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
