# Generated by Django 6.0.4 on 2026-07-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_diarios', '0003_gastodiario_tipo_cuenta'),
        ('usuarios', '0003_seed_administrativo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaccesousuario',
            name='numero_whatsapp',
            field=models.ForeignKey(blank=True, help_text='Número autorizado al que el bot le avisa las solicitudes asignadas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='gastos_diarios.numeroautorizado', verbose_name='Número de WhatsApp'),
        ),
    ]
