# Generated by Django 4.2.7 on 2026-02-28 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto Plantilla',
                'verbose_name_plural': 'Productos Plantilla',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CalculoEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs_json', models.TextField()),
                ('outputs_json', models.TextField()),
                ('errores_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='plantillas.productoplantilla')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Cálculo',
                'verbose_name_plural': 'Ejecuciones de Cálculo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('number', 'Número'), ('text', 'Texto'), ('bool', 'Sí/No'), ('select', 'Selección')], default='number', max_length=10)),
                ('unidad', models.CharField(blank=True, choices=[('', 'Sin unidad'), ('mm', 'Milímetros'), ('cm', 'Centímetros'), ('m', 'Metros'), ('m2', 'Metros cuadrados'), ('unidad', 'Unidad')], max_length=10)),
                ('modo', models.CharField(choices=[('MANUAL', 'Manual'), ('CALCULADO', 'Calculado')], default='MANUAL', max_length=10)),
                ('editable', models.BooleanField(default=True)),
                ('requerido', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('formula', models.TextField(blank=True, help_text='Fórmula para campos calculados (ej: ANCHO - 42)')),
                ('ayuda', models.CharField(blank=True, max_length=200)),
                ('opciones', models.TextField(blank=True, help_text='Opciones para tipo select, separadas por | (ej: BALCON|VENTANA|PUERTA)')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='plantillas.productoplantilla')),
            ],
            options={
                'verbose_name': 'Campo de Plantilla',
                'verbose_name_plural': 'Campos de Plantilla',
                'ordering': ['plantilla', 'orden', 'id'],
                'unique_together': {('plantilla', 'clave')},
            },
        ),
    ]
