# Generated by Django 4.2.7 on 2026-02-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_fabrica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Fábrica',
                'verbose_name_plural': 'Pedidos de Fábrica',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoFabricaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('inputs_json', models.TextField(default='{}')),
                ('outputs_json', models.TextField(default='{}')),
                ('errores_json', models.TextField(default='{}')),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('SIN_CALCULAR', 'Sin Calcular'), ('OK', 'OK'), ('ERROR', 'Con Errores')], default='SIN_CALCULAR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plantillas.pedidofabrica')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantillas.productoplantilla')),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
                'ordering': ['pedido', 'orden', 'id'],
            },
        ),
    ]
