# Generated by Django 4.2.7 on 2026-02-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_pedidofabrica_pedidofabricaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='errores_json',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='inputs_json',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='obs',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='outputs_json',
        ),
        migrations.CreateModel(
            name='PedidoFabricaFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('inputs_json', models.TextField(default='{}')),
                ('outputs_json', models.TextField(default='{}')),
                ('errores_json', models.TextField(default='{}')),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('SIN_CALCULAR', 'Sin Calcular'), ('OK', 'OK'), ('ERROR', 'Con Errores')], default='SIN_CALCULAR', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='plantillas.pedidofabricaitem')),
            ],
            options={
                'verbose_name': 'Fila de Item',
                'verbose_name_plural': 'Filas de Item',
                'ordering': ['item', 'orden', 'id'],
            },
        ),
    ]
