# Generated by Django 5.1.3 on 2026-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0005_remove_precio_opcionalfabrica"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcionalfabrica",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Precio"
            ),
        ),
    ]
