# Generated by Django 4.2.7 on 2026-03-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0005_remove_precio_opcionalfabrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaopcional',
            name='tipo_relacionador',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('hoja', 'Hoja'), ('vidrio', 'Vidrio')], default='perfil', max_length=20, verbose_name='Tipo'),
        ),
    ]
