# Generated by Django 5.1.3 on 2026-03-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0006_formulaopcional_tipo_relacionador"),
        ("plantillas", "0006_opcionalfabrica_precio"),
    ]

    operations = []
