# Generated by Django 4.2.7 on 2026-03-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0006_formulaopcional_tipo_relacionador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionProductoOpcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrusora_id', models.IntegerField(verbose_name='Extrusora ID')),
                ('linea_id', models.IntegerField(verbose_name='Línea ID')),
                ('producto_id', models.IntegerField(verbose_name='Producto ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_productos', to='plantillas.opcionalfabrica')),
            ],
            options={
                'verbose_name': 'Relación Producto-Opcional',
                'verbose_name_plural': 'Relaciones Producto-Opcional',
                'ordering': ['opcional', 'orden', 'id'],
            },
        ),
    ]
