# Generated by Django 4.2.7 on 2026-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0007_relacionproductoopcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionalfabrica',
            name='precio_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por m²'),
        ),
    ]
