# Generated by Django 4.2.7 on 2026-03-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0008_opcionalfabrica_precio_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionalfabrica',
            name='tipo',
            field=models.CharField(choices=[('mosquitero', 'Mosquitero'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='AccesorioOpcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(help_text='Fórmula para cantidad (ej: 2, CANTIDAD_HOJAS)', max_length=100, verbose_name='Cantidad')),
                ('accesorio', models.CharField(help_text='Código del accesorio', max_length=100, verbose_name='Accesorio')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios', to='plantillas.opcionalfabrica')),
            ],
            options={
                'verbose_name': 'Accesorio de Opcional',
                'verbose_name_plural': 'Accesorios de Opcionales',
                'ordering': ['opcional', 'orden', 'id'],
            },
        ),
    ]
