# Generated by Django 5.1.3 on 2026-03-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0009_merge_20260312_1628"),
        ("plantillas", "0009_opcionalfabrica_tipo_accesorioopcional"),
    ]

    operations = []
