# Generated by Django 5.1.3 on 2026-03-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0010_merge_20260312_1639"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opcionalfabrica",
            name="precio",
        ),
    ]
