# Generated by Django 6.0.4 on 2026-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0011_remove_opcionalfabrica_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionalfabrica',
            name='linea_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Línea ID'),
        ),
        migrations.AlterField(
            model_name='opcionalfabrica',
            name='tipo',
            field=models.CharField(choices=[('mosquitero', 'Mosquitero'), ('premarco', 'Premarco'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo'),
        ),
    ]
