# Generated by Django 6.0.4 on 2026-07-06 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0012_opcionalfabrica_linea_id_alter_opcionalfabrica_tipo'),
        ('presupuestos', '0011_presupuesto_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidofabrica',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_fabrica', to='presupuestos.presupuesto', verbose_name='Presupuesto de origen'),
        ),
    ]
