# Generated by Django 6.0.4 on 2026-07-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0013_pedidofabrica_presupuesto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campoplantilla',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campoplantilla',
            name='plantilla',
        ),
        migrations.RemoveField(
            model_name='pedidofabricafila',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidofabricaitem',
            name='plantilla',
        ),
        migrations.DeleteModel(
            name='CalculoEjecucion',
        ),
        migrations.DeleteModel(
            name='CampoPlantilla',
        ),
        migrations.DeleteModel(
            name='PedidoFabricaFila',
        ),
        migrations.DeleteModel(
            name='PedidoFabricaItem',
        ),
        migrations.DeleteModel(
            name='ProductoPlantilla',
        ),
    ]
