# Generated by Django 6.0.4 on 2026-07-07 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0014_eliminar_modelos_despiece'),
        ('presupuestos', '0011_presupuesto_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='N° de orden')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden en el pedido')),
                ('fecha_comprometida', models.DateField(blank=True, null=True, verbose_name='Fecha comprometida')),
                ('atendido_por', models.CharField(blank=True, max_length=150, verbose_name='Atendido por')),
                ('medicion_por', models.CharField(blank=True, max_length=150, verbose_name='Medición realizada por')),
                ('cliente_nombre', models.CharField(blank=True, max_length=200, verbose_name='Apellido y Nombre / Razón Social')),
                ('cliente_domicilio', models.CharField(blank=True, max_length=200, verbose_name='Domicilio')),
                ('cliente_piso', models.CharField(blank=True, max_length=20, verbose_name='Piso')),
                ('cliente_depto', models.CharField(blank=True, max_length=20, verbose_name='Depto.')),
                ('cliente_localidad', models.CharField(blank=True, max_length=120, verbose_name='Localidad')),
                ('cliente_mail', models.CharField(blank=True, max_length=150, verbose_name='Mail')),
                ('cliente_telefono', models.CharField(blank=True, max_length=80, verbose_name='Teléfono')),
                ('tipo_abertura', models.CharField(blank=True, max_length=150, verbose_name='Tipo de abertura')),
                ('linea', models.CharField(blank=True, max_length=150, verbose_name='Línea')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('mosquitero', models.CharField(blank=True, max_length=100, verbose_name='Mosquitero')),
                ('mosquitero_modelo', models.CharField(blank=True, max_length=150, verbose_name='Modelo de mosquitero')),
                ('travesano', models.CharField(blank=True, max_length=150, verbose_name='Travesaño')),
                ('tipo_marco', models.CharField(blank=True, max_length=150, verbose_name='Tipo de marco')),
                ('marco_desarmado', models.CharField(blank=True, max_length=100, verbose_name='Marco desarmado')),
                ('umbral_transitable', models.CharField(blank=True, max_length=100, verbose_name='Umbral transitable')),
                ('premarco', models.CharField(blank=True, max_length=100, verbose_name='Premarco')),
                ('guia_persiana', models.CharField(blank=True, max_length=100, verbose_name='Guía para persiana')),
                ('tipo_guia', models.CharField(blank=True, max_length=100, verbose_name='Tipo de guía')),
                ('tapacinta', models.CharField(blank=True, max_length=100, verbose_name='Tapacinta')),
                ('lado', models.CharField(blank=True, max_length=100, verbose_name='Lado')),
                ('modelo_hoja', models.CharField(blank=True, max_length=150, verbose_name='Modelo de hoja')),
                ('travesano_divisor', models.CharField(blank=True, max_length=100, verbose_name='Travesaño divisor')),
                ('altura_travesano', models.CharField(blank=True, max_length=100, verbose_name='Altura del travesaño')),
                ('cantidad_hojas', models.CharField(blank=True, max_length=50, verbose_name='Cantidad de hojas')),
                ('tipo_vidrio', models.CharField(blank=True, max_length=150, verbose_name='Tipo de vidrio')),
                ('contramarco', models.CharField(blank=True, max_length=100, verbose_name='Contramarco')),
                ('modelo_contramarco', models.CharField(blank=True, max_length=150, verbose_name='Modelo de contramarco')),
                ('tipo_trabajo', models.CharField(blank=True, max_length=150, verbose_name='Tipo de trabajo')),
                ('altura_trabajo', models.CharField(blank=True, max_length=100, verbose_name='Altura')),
                ('estructura', models.TextField(blank=True, verbose_name='Estructura')),
                ('nota', models.TextField(blank=True, verbose_name='Nota / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_fabricacion', to='presupuestos.itempresupuesto', verbose_name='Ítem de presupuesto de origen')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='plantillas.pedidofabrica', verbose_name='Pedido de fábrica')),
            ],
            options={
                'verbose_name': 'Orden de Fabricación',
                'verbose_name_plural': 'Órdenes de Fabricación',
                'ordering': ['pedido', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedidaOrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, verbose_name='Item')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('medida', models.CharField(blank=True, max_length=120, verbose_name='Medida')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('piso_depto', models.CharField(blank=True, max_length=80, verbose_name='Piso / Depto.')),
                ('orden_fila', models.PositiveIntegerField(default=0, verbose_name='Orden de fila')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='plantillas.ordenfabricacion', verbose_name='Orden de fabricación')),
            ],
            options={
                'verbose_name': 'Medida de Orden',
                'verbose_name_plural': 'Medidas de Orden',
                'ordering': ['orden', 'orden_fila', 'id'],
            },
        ),
    ]
