# Generated by Django 4.2.7 on 2026-01-27 19:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0002_remove_venta_monto_cobrado_cliente_condicion_iva_and_more'),
        ('productos', '0004_producto_alicuota_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], max_length=1)),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('iva_21', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_105', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_27', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cae', models.CharField(blank=True, max_length=14)),
                ('cae_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('observaciones_afip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto de Venta',
                'verbose_name_plural': 'Puntos de Venta',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='LibroIVAVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('neto_gravado_21', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_21', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_gravado_105', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_105', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_gravado_27', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_27', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Libro IVA Ventas',
                'verbose_name_plural': 'Libro IVA Ventas',
                'ordering': ['-periodo', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.puntoventa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_electronica', to='comercial.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('tipo', 'punto_venta', 'numero')},
        ),
    ]
